create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  company text not null,
  role text not null,
  location text default '',
  status text not null default 'Applied',
  applied_date date,
  job_url text default '',
  contact text default '',
  salary text default '',
  follow_up date,
  cover_letter text default 'No',
  referral text default 'No',
  last_updated date,
  interview_count integer not null default 0,
  notes text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.applications
  add column if not exists cover_letter text default 'No',
  add column if not exists referral text default 'No',
  add column if not exists last_updated date,
  add column if not exists interview_count integer not null default 0;

alter table public.applications
  alter column cover_letter set default 'No',
  alter column referral set default 'No';

update public.applications
set cover_letter = 'No'
where cover_letter is null or cover_letter = '';

update public.applications
set referral = 'No'
where referral is null or referral = '';

alter table public.applications enable row level security;

create policy "Users can read their applications"
  on public.applications
  for select
  to authenticated
  using (auth.uid() = user_id);

create policy "Users can create their applications"
  on public.applications
  for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "Users can update their applications"
  on public.applications
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their applications"
  on public.applications
  for delete
  to authenticated
  using (auth.uid() = user_id);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

alter function public.set_updated_at() set search_path = pg_catalog;

create index if not exists applications_user_id_idx
  on public.applications(user_id);

drop trigger if exists set_applications_updated_at on public.applications;

create trigger set_applications_updated_at
  before update on public.applications
  for each row
  execute function public.set_updated_at();

-- Job Agent phases 1-4: profile, resume, discovery, matching, and review.
create table public.job_agent_profiles (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  display_name text not null default '',
  phone text not null default '',
  location text not null default '',
  work_authorization text not null default '',
  first_name text not null default '',
  last_name text not null default '',
  preferred_name text not null default '',
  address_line_1 text not null default '',
  address_line_2 text not null default '',
  city text not null default '',
  region text not null default '',
  postal_code text not null default '',
  address_country_code text not null default 'ca'
    check (address_country_code ~ '^[a-z]{2}$'),
  formatted_address text not null default '',
  address_latitude numeric check (address_latitude is null or address_latitude between -90 and 90),
  address_longitude numeric check (address_longitude is null or address_longitude between -180 and 180),
  work_authorization_country text not null default 'ca'
    check (work_authorization_country ~ '^[a-z]{2}$'),
  work_authorization_status text not null default ''
    check (work_authorization_status in (
      '', 'citizen', 'permanent_resident', 'open_work_permit',
      'employer_specific_permit', 'student_work_authorization',
      'temporary_work_authorization', 'not_authorized', 'other',
      'prefer_not_to_say'
    )),
  work_authorization_details text not null default '',
  sponsorship_required boolean,
  future_sponsorship_required boolean,
  notice_period_days integer
    check (notice_period_days is null or notice_period_days between 0 and 365),
  skills text[] not null default '{}',
  years_experience integer check (years_experience is null or years_experience >= 0),
  reusable_answers jsonb not null default '{}'::jsonb
    check (jsonb_typeof(reusable_answers) = 'object'),
  automation_mode text not null default 'review'
    check (automation_mode in ('discover', 'review')),
  enabled boolean not null default false,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.resumes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  storage_path text not null unique,
  file_name text not null,
  mime_type text not null,
  file_size integer not null check (file_size > 0 and file_size <= 5242880),
  extracted_text text not null default '',
  skills text[] not null default '{}',
  is_primary boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index resumes_one_primary_per_user
  on public.resumes(user_id)
  where is_primary;

create table public.job_searches (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  titles text[] not null default '{}',
  locations text[] not null default '{}',
  remote_preference text not null default 'any'
    check (remote_preference in ('any', 'remote', 'hybrid', 'onsite')),
  work_arrangements text[] not null default array['remote', 'hybrid', 'onsite']::text[]
    check (work_arrangements <@ array['remote', 'hybrid', 'onsite']::text[]),
  seniority_levels text[] not null default '{}'
    check (seniority_levels <@ array['entry', 'mid', 'senior', 'staff', 'principal']::text[]),
  salary_min integer check (salary_min is null or salary_min >= 0),
  salary_max integer check (salary_max is null or salary_max >= 0),
  salary_currency text not null default 'CAD'
    check (salary_currency ~ '^[A-Z]{3}$'),
  check (salary_min is null or salary_max is null or salary_max >= salary_min),
  employment_types text[] not null default '{}',
  keywords text[] not null default '{}',
  excluded_keywords text[] not null default '{}',
  excluded_companies text[] not null default '{}',
  country_code text not null default 'ca'
    check (country_code ~ '^[a-z]{2}$'),
  enabled boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.job_alert_inboxes (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  address_alias text not null unique default replace(gen_random_uuid()::text, '-', '')
    check (address_alias ~ '^[a-z0-9]{20,64}$'),
  enabled boolean not null default true,
  last_received_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.job_alert_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null default 'unknown'
    check (provider in ('linkedin', 'indeed', 'unknown')),
  resend_email_id text not null unique,
  internet_message_id text not null default '',
  subject text not null default '',
  status text not null default 'received'
    check (status in ('received', 'processing', 'completed', 'partial', 'failed', 'ignored')),
  jobs_found integer not null default 0 check (jobs_found >= 0),
  jobs_created integer not null default 0 check (jobs_created >= 0),
  jobs_updated integer not null default 0 check (jobs_updated >= 0),
  parser_version text not null default 'v1',
  safe_error_summary text not null default '',
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.job_leads (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  job_search_id bigint not null references public.job_searches(id) on delete cascade,
  source_message_id bigint references public.job_alert_messages(id) on delete set null,
  source text not null check (source in ('linkedin', 'indeed')),
  external_id text not null,
  canonical_url text not null default '',
  apply_url text not null default '',
  company text not null,
  title text not null,
  location text not null default '',
  description text not null default '',
  category text not null default '',
  contract_type text not null default '',
  salary_min numeric,
  salary_max numeric,
  posted_at timestamptz,
  match_score smallint not null default 0
    check (match_score between 0 and 100),
  match_reasons text[] not null default '{}',
  filtered boolean not null default false,
  filter_reasons text[] not null default '{}',
  state text not null default 'new'
    check (state in ('new', 'shortlisted', 'dismissed', 'expired')),
  discovered_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, source, external_id)
);

create index job_alert_messages_user_received_idx
  on public.job_alert_messages(user_id, received_at desc);
create index job_alert_messages_user_provider_idx
  on public.job_alert_messages(user_id, provider, received_at desc);
create index job_leads_user_state_score_idx
  on public.job_leads(user_id, state, filtered, match_score desc);
create index job_leads_search_posted_idx
  on public.job_leads(job_search_id, posted_at desc);
create index job_leads_source_message_idx
  on public.job_leads(source_message_id)
  where source_message_id is not null;

alter table public.job_agent_profiles enable row level security;
alter table public.resumes enable row level security;
alter table public.job_searches enable row level security;
alter table public.job_alert_inboxes enable row level security;
alter table public.job_alert_messages enable row level security;
alter table public.job_leads enable row level security;

create policy "Users can read their job agent profile" on public.job_agent_profiles
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users can create their job agent profile" on public.job_agent_profiles
  for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Users can update their job agent profile" on public.job_agent_profiles
  for update to authenticated using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "Users can delete their job agent profile" on public.job_agent_profiles
  for delete to authenticated using ((select auth.uid()) = user_id);

create policy "Users can read their resume records" on public.resumes
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users can create their resume records" on public.resumes
  for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Users can update their resume records" on public.resumes
  for update to authenticated using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "Users can delete their resume records" on public.resumes
  for delete to authenticated using ((select auth.uid()) = user_id);

create policy "Users can read their job search" on public.job_searches
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users can create their job search" on public.job_searches
  for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Users can update their job search" on public.job_searches
  for update to authenticated using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "Users can delete their job search" on public.job_searches
  for delete to authenticated using ((select auth.uid()) = user_id);

create policy "Users can read their job alert inbox" on public.job_alert_inboxes
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users can create their job alert inbox" on public.job_alert_inboxes
  for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Users can update their job alert inbox" on public.job_alert_inboxes
  for update to authenticated using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "Users can delete their job alert inbox" on public.job_alert_inboxes
  for delete to authenticated using ((select auth.uid()) = user_id);
create policy "Users can read their job alert history" on public.job_alert_messages
  for select to authenticated using ((select auth.uid()) = user_id);

create policy "Users can read their job leads" on public.job_leads
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users can review their job leads" on public.job_leads
  for update to authenticated using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create trigger set_job_agent_profiles_updated_at before update on public.job_agent_profiles
  for each row execute function public.set_updated_at();
create trigger set_resumes_updated_at before update on public.resumes
  for each row execute function public.set_updated_at();
create trigger set_job_searches_updated_at before update on public.job_searches
  for each row execute function public.set_updated_at();
create trigger set_job_alert_inboxes_updated_at before update on public.job_alert_inboxes
  for each row execute function public.set_updated_at();
create trigger set_job_leads_updated_at before update on public.job_leads
  for each row execute function public.set_updated_at();

grant usage on schema public to authenticated;

revoke all on public.job_agent_profiles from anon, authenticated;
revoke all on public.resumes from anon, authenticated;
revoke all on public.job_searches from anon, authenticated;
revoke all on public.job_alert_inboxes from anon, authenticated;
revoke all on public.job_alert_messages from anon, authenticated;
revoke all on public.job_leads from anon, authenticated;
revoke all on sequence public.job_agent_profiles_id_seq from anon, authenticated;
revoke all on sequence public.resumes_id_seq from anon, authenticated;
revoke all on sequence public.job_searches_id_seq from anon, authenticated;
revoke all on sequence public.job_alert_inboxes_id_seq from anon, authenticated;
revoke all on sequence public.job_alert_messages_id_seq from anon, authenticated;
revoke all on sequence public.job_leads_id_seq from anon, authenticated;

grant select, insert, update, delete on public.job_agent_profiles to authenticated;
grant select, insert, update, delete on public.resumes to authenticated;
grant select, insert, update, delete on public.job_searches to authenticated;
grant select, insert, update, delete on public.job_alert_inboxes to authenticated;
grant select on public.job_alert_messages to authenticated;
grant select on public.job_leads to authenticated;
grant update (state) on public.job_leads to authenticated;
grant usage, select on sequence public.job_agent_profiles_id_seq to authenticated;
grant usage, select on sequence public.resumes_id_seq to authenticated;
grant usage, select on sequence public.job_searches_id_seq to authenticated;
grant usage, select on sequence public.job_alert_inboxes_id_seq to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'resumes', 'resumes', false, 5242880,
  array['application/pdf', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'text/plain']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "Users can read their resume files" on storage.objects
  for select to authenticated using (
    bucket_id = 'resumes' and (storage.foldername(name))[1] = (select auth.uid())::text
  );
create policy "Users can upload their resume files" on storage.objects
  for insert to authenticated with check (
    bucket_id = 'resumes' and (storage.foldername(name))[1] = (select auth.uid())::text
  );
create policy "Users can replace their resume files" on storage.objects
  for update to authenticated using (
    bucket_id = 'resumes' and (storage.foldername(name))[1] = (select auth.uid())::text
  ) with check (
    bucket_id = 'resumes' and (storage.foldername(name))[1] = (select auth.uid())::text
  );
create policy "Users can delete their resume files" on storage.objects
  for delete to authenticated using (
    bucket_id = 'resumes' and (storage.foldername(name))[1] = (select auth.uid())::text
  );
