create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  company text not null,
  role text not null,
  location text default '',
  status text not null default 'Applied',
  applied_date date,
  job_url text default '',
  contact text default '',
  salary text default '',
  follow_up date,
  cover_letter text default '',
  referral text default '',
  last_updated date,
  notes text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.applications
  add column if not exists cover_letter text default '',
  add column if not exists referral text default '',
  add column if not exists last_updated date;

alter table public.applications enable row level security;

create policy "Users can read their applications"
  on public.applications
  for select
  to authenticated
  using (auth.uid() = user_id);

create policy "Users can create their applications"
  on public.applications
  for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "Users can update their applications"
  on public.applications
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their applications"
  on public.applications
  for delete
  to authenticated
  using (auth.uid() = user_id);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_applications_updated_at on public.applications;

create trigger set_applications_updated_at
  before update on public.applications
  for each row
  execute function public.set_updated_at();
