import { expect, test } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { application, backend, lead, nav, noOverflow, signIn, spreadsheet } from './fixtures.js'

test('CRUD, details, sorting, filtering, pagination and persisted refresh', async ({ page, context }) => {
  const state = await backend(context, Array.from({ length: 25 }, (_, i) => application(i + 1, i === 0 ? { status: 'Rejected', last_updated: '2027-01-01' } : {})))
  await signIn(page)
  await nav(page, 'List')
  await expect(page.locator('.application-card')).toHaveCount(10)
  await expect(page.locator('.application-card').first()).toContainText('Synthetic 25')
  await page.getByRole('combobox', { name: 'Sort', exact: true }).selectOption('lastUpdated')
  await expect(page.locator('.application-card').first()).toContainText('Synthetic 1')
  await page.getByRole('combobox', { name: 'Status', exact: true }).selectOption('Rejected')
  await expect(page.locator('.application-card')).toHaveCount(1)
  await expect(page.locator('.application-card')).toContainText('Synthetic 1')
  await nav(page, 'Clear filters')
  await page.getByRole('button', { name: 'Next', exact: true }).first().click()
  await expect(page.getByText('Page 2 of 3').first()).toBeVisible()
  await page.getByLabel('Search', { exact: true }).fill('Synthetic 25')
  await expect(page.locator('.application-card')).toHaveCount(1)
  await nav(page, 'Clear filters')
  await nav(page, 'Add application')
  await page.getByLabel('Company', { exact: false }).fill('Created fixture')
  await page.getByLabel('Role', { exact: false }).fill('Auditor')
  await page.getByLabel('Notes', { exact: true }).fill('Persisted audit note')
  await page.locator('button[type="submit"]').click()
  await expect(page.getByText('Created fixture', { exact: true })).toBeVisible()
  await nav(page, 'List')
  await page.getByLabel('Search', { exact: true }).fill('Created fixture')
  await nav(page, 'Edit')
  await page.getByLabel('Role', { exact: false }).fill('Updated auditor')
  await page.locator('button[type="submit"]').click()
  await expect(page.getByText('Updated auditor', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('Created fixture', { exact: true })).toBeVisible()
  expect(state.applications.find((row) => row.company === 'Created fixture').role).toBe('Updated auditor')
  await nav(page, 'List')
  await page.getByLabel('Search', { exact: true }).fill('Created fixture')
  page.once('dialog', (dialog) => dialog.accept())
  await nav(page, 'Delete')
  await expect(page.getByText('Created fixture', { exact: true })).toHaveCount(0)
  expect(state.blocked).toEqual([])
})

test('BUG: board select-all selects ten of twenty-five rendered cards; canceled delete clears selection', async ({ page, context }) => {
  const state = await backend(context, Array.from({ length: 25 }, (_, i) => application(i + 1)))
  await signIn(page)
  await expect(page.locator('.board-card')).toHaveCount(25)
  await nav(page, 'Enter multi-select')
  await nav(page, 'Select all')
  await expect(page.getByText('10 selected', { exact: true })).toBeVisible()
  page.once('dialog', (dialog) => dialog.dismiss())
  await nav(page, 'Delete selected')
  await expect(page.getByText('0 selected', { exact: true })).toBeVisible()
  expect(state.applications).toHaveLength(25)
})

test('BUG: failed bulk delete clears selection and does not announce dashboard error', async ({ page, context }) => {
  const state = await backend(context, [application(1)])
  state.failDelete = true
  await signIn(page)
  await nav(page, 'Enter multi-select')
  await nav(page, 'Select all')
  page.once('dialog', (dialog) => dialog.accept())
  await nav(page, 'Delete selected')
  await expect(page.locator('.form-error')).toContainText('Synthetic delete failure')
  await expect(page.getByText('0 selected', { exact: true })).toBeVisible()
  await expect(page.locator('.form-error')).not.toHaveAttribute('role', 'alert')
  expect(state.applications).toHaveLength(1)
})

test('BUG: out-of-order status responses leave UI stale until reload', async ({ page, context }) => {
  const state = await backend(context, [application(1)])
  state.holdUpdates = true
  await signIn(page)
  const status = page.locator('.board-card select')
  await status.selectOption('Interview')
  await expect.poll(() => state.pending.length).toBe(1)
  await status.selectOption('Rejected')
  await expect.poll(() => state.pending.length).toBe(2)
  await state.pending[1]()
  await state.pending[0]()
  await expect(status).toHaveValue('Interview')
  expect(state.applications[0].status).toBe('Rejected')
  await page.reload()
  await expect(page.locator('.board-card select')).toHaveValue('Rejected')
})

test('BUG: API note labels disappear and nullable notes prevent dashboard loading', async ({ page, context }) => {
  const state = await backend(context, [application(1, { notes: 'Cover letter: Yes\nKeep this note' })])
  await signIn(page)
  await nav(page, 'Edit')
  await expect(page.getByRole('textbox', { name: 'Notes', exact: true })).toHaveValue('Keep this note')
  await page.getByLabel('Role', { exact: false }).fill('Updated')
  await page.locator('button[type="submit"]').click()
  await expect.poll(() => state.applications[0].notes).toBe('Keep this note')
  state.applications[0].notes = null
  await page.reload()
  await expect(page.locator('.form-error')).toContainText('match')
  await expect(page.locator('.board-card')).toHaveCount(0)
})

test('CQ: hidden dashboard interview calculation differs from progress for zero rounds', async ({ page, context }) => {
  await backend(context, [application(1, { status: 'Interview', interview_count: 0 })])
  await signIn(page)
  await expect(page.getByText('0 applications reached interview')).toHaveText('0 applications reached interview')
  await nav(page, 'Progress')
  await expect(page.locator('.progress-summary article').filter({ hasText: 'Reached interview' }).locator('strong')).toHaveText('1')
})

test('BUG: demo password succeeds without persistence; all demo navigation stays local', async ({ page, context }) => {
  const state = await backend(context)
  await page.goto('/#/demo')
  await nav(page, 'Add application')
  await page.getByLabel('Company', { exact: false }).fill('Demo audit fixture')
  await page.getByLabel('Role', { exact: false }).fill('Auditor')
  await page.locator('button[type="submit"]').click()
  await nav(page, 'Progress')
  await nav(page, 'Dashboard')
  await expect(page.getByText('Demo audit fixture', { exact: true })).toBeVisible()
  await nav(page, 'Profile')
  await page.getByLabel('New password', { exact: true }).fill('synthetic-new-password')
  await page.getByLabel('Confirm password', { exact: true }).fill('synthetic-new-password')
  await nav(page, 'Update password')
  await expect(page.getByRole('status')).toHaveText('Password updated successfully.')
  expect(state.requests).toEqual([])
  expect(state.blocked).toEqual([])
})

test('Excel import duplicate selection and atomic failure feedback', async ({ page, context }) => {
  const state = await backend(context, [application(1, { company: 'Existing', role: 'Engineer', applied_date: '2026-01-01' })])
  await signIn(page)
  await nav(page, 'Import Excel')
  await page.locator('input[type="file"]').setInputFiles(spreadsheet([
    ['Company', 'Role', 'Applied Date', 'Notes'],
    ['Existing', 'Engineer', '2026-01-01', 'duplicate'],
    ['Imported', 'Auditor', '2026-12-31', 'must persist'],
  ]))
  await expect(page.getByText(/duplicate/i).first()).toBeVisible()
  state.failInsert = true
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: /Import 1/ }).click()
  await expect(page.getByRole('alert')).toContainText('Synthetic insert failure')
  expect(state.applications).toHaveLength(1)
  state.failInsert = false
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: /Import 1/ }).click()
  await expect(page.getByRole('status')).toContainText('1 application')
  expect(state.applications.at(-1).notes).toBe('must persist')
  await nav(page, 'Dashboard')
  await expect(page.getByText('Imported', { exact: true })).toBeVisible()
})

test('Job conversion, pagination top scroll, filter and remove; BUG empty search mislabels queue', async ({ page, context }) => {
  const state = await backend(context, [], Array.from({ length: 25 }, (_, i) => lead(i + 1)))
  await signIn(page)
  await page.goto('/#/job-agent/matches')
  await expect(page.locator('.agent-lead')).toHaveCount(20)
  await nav(page, 'Next')
  await expect(page.locator('.agent-lead')).toHaveCount(5)
  await expect.poll(() => page.evaluate(() => scrollY)).toBe(0)
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Finished applying' }).first().click()
  await expect(page.locator('.agent-lead')).toHaveCount(4)
  expect(state.applications).toHaveLength(1)
  await page.getByLabel('Search jobs waiting to be applied').fill('no-such-job')
  await expect(page.getByRole('heading', { name: 'No applications waiting' })).toBeVisible()
  expect(state.leads.filter((row) => row.state === 'new')).toHaveLength(24)
  await page.getByLabel('Search jobs waiting to be applied').fill('')
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Remove', exact: true }).first().click()
  await expect.poll(() => state.leads.length).toBe(24)
  await nav(page, 'Dashboard')
  await expect(page.locator('.metric-card-total strong')).toHaveText('1')
  expect(state.blocked).toEqual([])
})

test('BUG: remove all uses only fetched 500 leads and leaves an unseen lead', async ({ page, context }) => {
  const state = await backend(context, [], Array.from({ length: 501 }, (_, i) => lead(i + 1)))
  await signIn(page)
  await page.goto('/#/job-agent/matches')
  await expect(page.getByText('500 waiting')).toBeVisible()
  page.once('dialog', (dialog) => dialog.accept())
  await nav(page, 'Remove all')
  await expect(page.getByRole('heading', { name: 'No applications waiting' })).toBeVisible()
  expect(state.leads).toHaveLength(1)
  await page.reload()
  await expect(page.getByText('1 waiting')).toBeVisible()
})

for (const width of [1440, 768, 390]) {
  test(`responsive public demo workflows, keyboard labels and overflow at ${width}px`, async ({ page, context }, info) => {
    await page.setViewportSize({ width, height: 900 })
    const state = await backend(context)
    await page.goto('/#/demo')
    for (const [name, heading] of [
      ['Dashboard', 'Your application pipeline'], ['Profile', 'Demo'],
      ['Progress', 'Your application flow.'], ['Import Excel', 'Bring in your existing tracker.'],
      ['Job Agent', 'Turn job alerts into an application queue.'],
    ]) {
      // The compact bottom bar uses shortened names.
      await nav(page, width <= 900 && name === 'Import Excel' ? 'Import' : width <= 900 && name === 'Job Agent' ? 'Agent' : name)
      await expect(page.getByRole('heading', { name: heading, exact: true, level: 1 })).toBeVisible()
      await noOverflow(page)
      await page.screenshot({ path: info.outputPath(`${name.replaceAll(' ', '-')}-${width}.png`), fullPage: true })
    }
    await nav(page, 'Profile')
    await page.getByLabel('New password', { exact: true }).focus()
    await expect(page.getByLabel('New password', { exact: true })).toBeFocused()
    await page.keyboard.press('Tab')
    await expect(page.getByRole('button', { name: 'Show new password' })).toBeFocused()
    await nav(page, width <= 900 ? 'Agent' : 'Job Agent')
    await nav(page, 'Matches')
    await expect(page.getByRole('heading', { name: 'Jobs waiting for you' })).toBeVisible()
    await noOverflow(page)
    await page.screenshot({ path: info.outputPath(`Matches-${width}.png`), fullPage: true })
    await nav(page, 'Dashboard')
    await nav(page, 'Add application')
    await expect(page.getByRole('heading', { name: 'Add a new application', exact: true })).toBeVisible()
    await noOverflow(page)
    await page.screenshot({ path: info.outputPath(`Form-${width}.png`), fullPage: true })
    expect(state.requests).toEqual([])
    expect(state.blocked).toEqual([])
  })
}

test('BUG: both Sign out controls are hidden throughout tablet breakpoint', async ({ page, context }, info) => {
  await backend(context)
  await signIn(page)
  await nav(page, 'Profile')
  for (const width of [722, 768, 898]) {
    await page.setViewportSize({ width, height: 900 })
    await expect.poll(() => page.evaluate(() => innerWidth)).toBe(width)
    await expect(page.getByRole('button', { name: 'Sign out', exact: true }).filter({ visible: true })).toHaveCount(0)
  }
  await page.screenshot({ path: info.outputPath('tablet-no-sign-out.png'), fullPage: true })
  for (const width of [390, 902, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    await expect.poll(() => page.evaluate(() => innerWidth)).toBe(width)
    await expect(page.getByRole('button', { name: 'Sign out', exact: true }).filter({ visible: true })).toHaveCount(1)
  }
  const boundaries = []
  for (const width of [720, 721, 900, 901]) {
    await page.setViewportSize({ width, height: 900 })
    await expect.poll(() => page.evaluate(() => innerWidth)).toBe(width)
    const media = await page.evaluate(() => ({ width: innerWidth, mobile: matchMedia('(max-width: 720px)').matches, compact: matchMedia('(max-width: 900px)').matches, visualWidth: visualViewport.width, dpr: devicePixelRatio }))
    const expected = media.compact && !media.mobile ? 0 : 1
    await expect(page.getByRole('button', { name: 'Sign out', exact: true }).filter({ visible: true })).toHaveCount(expected)
    boundaries.push({ ...media, visibleSignOut: expected })
  }
  await info.attach('breakpoint-observations', { body: JSON.stringify(boundaries, null, 2), contentType: 'application/json' })
  console.log(JSON.stringify({ browser: info.project.name, boundaries }))
})

test('BUG: whitespace required fields silently return without saving or showing error', async ({ page, context }) => {
  const state = await backend(context)
  await signIn(page)
  await nav(page, 'Add application')
  await page.getByLabel('Company', { exact: false }).fill('   ')
  await page.getByLabel('Role', { exact: false }).fill('   ')
  await page.locator('button[type="submit"]').click()
  await expect(page.locator('button[type="submit"]')).toBeEnabled()
  await expect(page.getByRole('alert')).toHaveCount(0)
  expect(state.requests.filter((request) => request.table === 'applications' && request.method === 'POST')).toHaveLength(0)
})

test('BUG: save response navigates away from the page chosen during pending operation', async ({ page, context }) => {
  const state = await backend(context)
  state.holdInserts = true
  await signIn(page)
  await nav(page, 'Add application')
  await page.getByLabel('Company', { exact: false }).fill('Pending fixture')
  await page.getByLabel('Role', { exact: false }).fill('Auditor')
  await page.locator('button[type="submit"]').click()
  await expect.poll(() => state.pending.length).toBe(1)
  await nav(page, 'Progress')
  await expect(page).toHaveURL(/progress$/)
  await state.pending[0]()
  await expect(page).toHaveURL(/dashboard$/)
})

test('BUG: editing a rejected record moves its historical rejection date', async ({ page, context }) => {
  await page.clock.setFixedTime(new Date('2026-01-09T17:00:00Z'))
  const state = await backend(context, [application(1, { status: 'Rejected', applied_date: '2025-12-30', last_updated: '2025-12-31' })])
  await signIn(page)
  await nav(page, 'Progress')
  await nav(page, 'Calendar')
  await expect(page.locator('.calendar-range')).toContainText('2025')
  await expect(page.locator('.calendar-event-rejected')).toHaveCount(1)
  await nav(page, 'Dashboard')
  await nav(page, 'Edit')
  await page.getByLabel('Notes', { exact: true }).fill('Only a note changed')
  await page.locator('button[type="submit"]').click()
  await expect.poll(() => state.applications[0].last_updated).toBe('2026-01-09')
  await nav(page, 'Progress')
  await nav(page, 'Calendar')
  await expect(page.locator('.calendar-range')).toContainText('January 4')
  await expect(page.locator('.calendar-event-rejected')).toHaveCount(1)
  await nav(page, 'Previous week')
  await expect(page.locator('.calendar-event-rejected')).toHaveCount(0)
})

test('public demo edit, delete, bulk import, inbox pause/rotate and lead conversion are consistent', async ({ page, context }) => {
  const state = await backend(context)
  await page.goto('/#/demo')
  await page.getByRole('button', { name: 'Edit', exact: true }).first().click()
  await page.getByLabel('Role', { exact: false }).fill('Demo edited role')
  await page.locator('button[type="submit"]').click()
  await expect(page.getByText('Demo edited role', { exact: true })).toBeVisible()
  await nav(page, 'List')
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Delete', exact: true }).first().click()
  await nav(page, 'Enter multi-select')
  await nav(page, 'Select all')
  page.once('dialog', (dialog) => dialog.accept())
  await nav(page, 'Delete selected')
  await expect(page.locator('.application-card')).toHaveCount(0)
  await nav(page, 'Import Excel')
  await page.locator('input[type="file"]').setInputFiles(spreadsheet([['Company', 'Role'], ['Demo imported', 'Engineer']]))
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: /Import 1/ }).click()
  await expect(page.getByRole('status')).toContainText('imported successfully')
  await nav(page, 'Job Agent')
  await nav(page, 'Pause imports')
  await expect(page.getByRole('button', { name: 'Resume imports' })).toBeVisible()
  await nav(page, 'Resume imports')
  page.once('dialog', (dialog) => dialog.accept())
  await nav(page, 'Replace address')
  await nav(page, 'Matches')
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Finished applying' }).first().click()
  await nav(page, 'Dashboard')
  await expect(page.locator('.metric-card-total strong')).toHaveText('2')
  expect(state.requests).toEqual([])
})

test('accessibility evidence and measured 1000-row board/list rendering', async ({ page, context }, info) => {
  test.setTimeout(120000)
  await backend(context, Array.from({ length: 1000 }, (_, i) => application(i + 1)))
  const started = Date.now()
  await signIn(page)
  await expect(page.locator('.board-card')).toHaveCount(1000)
  const boardMs = Date.now() - started
  const listStarted = Date.now()
  await nav(page, 'List')
  await expect(page.locator('.application-card')).toHaveCount(10)
  const listMs = Date.now() - listStarted
  const findings = []
  for (const name of ['Dashboard', 'Profile', 'Progress', 'Import Excel', 'Job Agent']) {
    await nav(page, name)
    const results = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
    findings.push({ page: name, violations: results.violations.map((v) => ({ id: v.id, impact: v.impact, nodes: v.nodes.map((n) => ({ target: n.target, summary: n.failureSummary })) })) })
  }
  await info.attach('sanitized-audit-measurements', { body: JSON.stringify({ boardMs, listMs, findings }, null, 2), contentType: 'application/json' })
  console.log(JSON.stringify({ browser: info.project.name, boardMs, listMs, accessibility: findings.map((item) => ({ page: item.page, ids: item.violations.map((v) => v.id) })) }))
})
