create table public.job_agent_profiles (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  display_name text not null default '',
  phone text not null default '',
  location text not null default '',
  work_authorization text not null default '',
  sponsorship_required boolean,
  skills text[] not null default '{}',
  years_experience integer check (years_experience is null or years_experience >= 0),
  reusable_answers jsonb not null default '{}'::jsonb
    check (jsonb_typeof(reusable_answers) = 'object'),
  automation_mode text not null default 'review'
    check (automation_mode in ('discover', 'review')),
  enabled boolean not null default false,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.resumes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  storage_path text not null unique,
  file_name text not null,
  mime_type text not null,
  file_size integer not null check (file_size > 0 and file_size <= 5242880),
  extracted_text text not null default '',
  skills text[] not null default '{}',
  is_primary boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index resumes_one_primary_per_user
  on public.resumes(user_id)
  where is_primary;

create table public.job_searches (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  titles text[] not null default '{}',
  locations text[] not null default '{}',
  remote_preference text not null default 'any'
    check (remote_preference in ('any', 'remote', 'hybrid', 'onsite')),
  salary_min integer check (salary_min is null or salary_min >= 0),
  employment_types text[] not null default '{}',
  keywords text[] not null default '{}',
  excluded_keywords text[] not null default '{}',
  excluded_companies text[] not null default '{}',
  country_code text not null default 'ca'
    check (country_code ~ '^[a-z]{2}$'),
  source text not null default 'adzuna'
    check (source = 'adzuna'),
  enabled boolean not null default false,
  last_scanned_at timestamptz,
  next_scan_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.job_scan_runs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  job_search_id bigint references public.job_searches(id) on delete set null,
  trigger_type text not null default 'scheduled'
    check (trigger_type in ('scheduled', 'manual')),
  status text not null default 'running'
    check (status in ('running', 'completed', 'failed', 'skipped')),
  fetched_count integer not null default 0 check (fetched_count >= 0),
  created_count integer not null default 0 check (created_count >= 0),
  matched_count integer not null default 0 check (matched_count >= 0),
  error_summary text not null default '',
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

create table public.job_leads (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  job_search_id bigint not null references public.job_searches(id) on delete cascade,
  source text not null,
  external_id text not null,
  canonical_url text not null default '',
  apply_url text not null default '',
  company text not null,
  title text not null,
  location text not null default '',
  description text not null default '',
  category text not null default '',
  contract_type text not null default '',
  salary_min numeric,
  salary_max numeric,
  posted_at timestamptz,
  match_score smallint not null default 0
    check (match_score between 0 and 100),
  match_reasons text[] not null default '{}',
  filtered boolean not null default false,
  filter_reasons text[] not null default '{}',
  state text not null default 'new'
    check (state in ('new', 'shortlisted', 'dismissed', 'expired')),
  discovered_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, source, external_id)
);

create index job_scan_runs_user_started_idx
  on public.job_scan_runs(user_id, started_at desc);

create index job_leads_user_state_score_idx
  on public.job_leads(user_id, state, filtered, match_score desc);

create index job_leads_search_posted_idx
  on public.job_leads(job_search_id, posted_at desc);

alter table public.job_agent_profiles enable row level security;
alter table public.resumes enable row level security;
alter table public.job_searches enable row level security;
alter table public.job_scan_runs enable row level security;
alter table public.job_leads enable row level security;

create policy "Users can read their job agent profile"
  on public.job_agent_profiles for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can create their job agent profile"
  on public.job_agent_profiles for insert to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Users can update their job agent profile"
  on public.job_agent_profiles for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users can delete their job agent profile"
  on public.job_agent_profiles for delete to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can read their resume records"
  on public.resumes for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can create their resume records"
  on public.resumes for insert to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Users can update their resume records"
  on public.resumes for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users can delete their resume records"
  on public.resumes for delete to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can read their job search"
  on public.job_searches for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can create their job search"
  on public.job_searches for insert to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Users can update their job search"
  on public.job_searches for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users can delete their job search"
  on public.job_searches for delete to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can read their scan history"
  on public.job_scan_runs for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can read their job leads"
  on public.job_leads for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can review their job leads"
  on public.job_leads for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create trigger set_job_agent_profiles_updated_at
  before update on public.job_agent_profiles
  for each row execute function public.set_updated_at();

create trigger set_resumes_updated_at
  before update on public.resumes
  for each row execute function public.set_updated_at();

create trigger set_job_searches_updated_at
  before update on public.job_searches
  for each row execute function public.set_updated_at();

create trigger set_job_leads_updated_at
  before update on public.job_leads
  for each row execute function public.set_updated_at();

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.job_agent_profiles to authenticated;
grant select, insert, update, delete on public.resumes to authenticated;
grant select, insert, update, delete on public.job_searches to authenticated;
grant select on public.job_scan_runs to authenticated;
grant select on public.job_leads to authenticated;
grant update (state) on public.job_leads to authenticated;
grant usage, select on sequence public.job_agent_profiles_id_seq to authenticated;
grant usage, select on sequence public.resumes_id_seq to authenticated;
grant usage, select on sequence public.job_searches_id_seq to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'resumes',
  'resumes',
  false,
  5242880,
  array[
    'application/pdf',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'text/plain'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "Users can read their resume files"
  on storage.objects for select to authenticated
  using (
    bucket_id = 'resumes'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

create policy "Users can upload their resume files"
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'resumes'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

create policy "Users can replace their resume files"
  on storage.objects for update to authenticated
  using (
    bucket_id = 'resumes'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  )
  with check (
    bucket_id = 'resumes'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

create policy "Users can delete their resume files"
  on storage.objects for delete to authenticated
  using (
    bucket_id = 'resumes'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );
