create table public.job_alert_inboxes (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  address_alias text not null unique default replace(gen_random_uuid()::text, '-', '')
    check (address_alias ~ '^[a-z0-9]{20,64}$'),
  enabled boolean not null default true,
  last_received_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.job_alert_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null default 'unknown'
    check (provider in ('linkedin', 'indeed', 'unknown')),
  resend_email_id text not null unique,
  internet_message_id text not null default '',
  subject text not null default '',
  status text not null default 'received'
    check (status in ('received', 'processing', 'completed', 'partial', 'failed', 'ignored')),
  jobs_found integer not null default 0 check (jobs_found >= 0),
  jobs_created integer not null default 0 check (jobs_created >= 0),
  jobs_updated integer not null default 0 check (jobs_updated >= 0),
  parser_version text not null default 'v1',
  safe_error_summary text not null default '',
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.job_searches
  drop constraint if exists job_searches_source_check;
alter table public.job_searches
  alter column source set default 'email_alerts';
alter table public.job_searches
  add constraint job_searches_source_check
  check (source in ('adzuna', 'email_alerts'));

alter table public.job_leads
  add column source_message_id bigint
  references public.job_alert_messages(id) on delete set null;

create index job_alert_messages_user_received_idx
  on public.job_alert_messages(user_id, received_at desc);
create index job_alert_messages_user_provider_idx
  on public.job_alert_messages(user_id, provider, received_at desc);
create index job_leads_source_message_idx
  on public.job_leads(source_message_id)
  where source_message_id is not null;

alter table public.job_alert_inboxes enable row level security;
alter table public.job_alert_messages enable row level security;

create policy "Users can read their job alert inbox" on public.job_alert_inboxes
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users can create their job alert inbox" on public.job_alert_inboxes
  for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Users can update their job alert inbox" on public.job_alert_inboxes
  for update to authenticated using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "Users can delete their job alert inbox" on public.job_alert_inboxes
  for delete to authenticated using ((select auth.uid()) = user_id);
create policy "Users can read their job alert history" on public.job_alert_messages
  for select to authenticated using ((select auth.uid()) = user_id);

create trigger set_job_alert_inboxes_updated_at
  before update on public.job_alert_inboxes
  for each row execute function public.set_updated_at();

revoke all on public.job_alert_inboxes from anon, authenticated;
revoke all on public.job_alert_messages from anon, authenticated;
revoke all on sequence public.job_alert_inboxes_id_seq from anon, authenticated;
revoke all on sequence public.job_alert_messages_id_seq from anon, authenticated;

grant select, insert, update, delete on public.job_alert_inboxes to authenticated;
grant select on public.job_alert_messages to authenticated;
grant usage, select on sequence public.job_alert_inboxes_id_seq to authenticated;
